[package]
name = "obddimal_divide_and_conquer"
version = "0.1.0"
authors = ["Christian Valenti <christian.valenti97@gmail.com>"]
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
petgraph = "0.6.2"
obddimal = { path = "./../.." }
